---

- hosts: all
  become: yes
  roles:
    - odoku.ntp


- hosts: api
  become: yes
  vars_files:
    - vars/common.yml
  roles:
    - leonidas.nvm
    - role: franklinkim.environment
      environment_config:
        APP_SECRET: xxxx
        APP_PORT: 9000
        DB_HOST: 127.0.0.1
        DB_USER: root
        DB_PASSWORD: hogehoge
        DB_NAME: mr_koala_sample_api


- hosts: db
  become: yes
  vars_files:
    - vars/common.yml
  roles:
    - geerlingguy.mysql
