---
version: '2'

services:
  app:
    build: .
    container_name: sample-api
    depends_on:
      - db
    entrypoint: ./docker/libs/wait-for-it/wait-for-it.sh db:3306 -- npm run serve
    volumes:
      - ./models:/src/models
      - ./migrations:/src/migrations
      - ./resources:/src/resources
      - ./seeds:/src/seeds
      - ./index.js:/src/index.js
      - ./knexfile.js:/src/knexfile.js
      - ./package.json:/src/package.json
    ports:
      - 9001:9001
  db:
    image: "mysql:5.6"
    container_name: sample-db
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - "3306:3306"
