---
version: '2'

services:
  app:
    build: .
    container_name: bike-api
    command: npm run serve
    volumes:
      - ./resources:/src/resources
      - ./index.js:/src/index.js
      - ./package.json:/src/package.json
    ports:
      - 9001:9001
  db:
    image: "mysql:5.6"
    container_name: bike-db
    environment:
      MYSQL_ROOT_PASSWORD: hogehoge
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - "3306:3306"
