---
version: '2'

services:
  app:
    build: .
    container_name: sample-api
    command: ./docker/app/start.sh
    depends_on:
      - db
    volumes:
      - .:/src
    ports:
      - 9001:9001
  db:
    image: "mysql:5.6"
    container_name: sample-db
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - "3306:3306"
