---
version: '2'

services:
  app:
    build: .
    container_name: sample-api
    command: npm run serve
    environment:
      APP_SECRET: xxxx
      APP_PORT: 9000
      DB_CLIENT: mysql
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: hogehoge
      DB_NAME: bike_api
      DB_MIGRATION_TABLE: migrations
    depends_on:
      - db
    volumes:
      - ./migrations:/src/migrations
      - ./models:/src/models
      - ./resources:/src/resources
      - ./seeds:/src/seeds
      - ./api.raml:/src/api.raml
      - ./api08.raml:/src/api08.raml
      - ./index.js:/src/index.js
      - ./config.js:/src/config.js
      - ./package.json:/src/package.json
    ports:
      - 9000:9000
  db:
    image: "mysql:5.6"
    container_name: sample-db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - "3306:3306"
